services:
  vehicle-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vehicle_db
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    networks:
      - vehicle-network
    volumes:
      - vehicle_db_data:/var/opt/mssql
    restart: unless-stopped

  vehicle-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle_service
    environment:
      ConnectionStrings__DefaultConnection: "Server=vehicle-db,1433;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;Connection Timeout=30;"
      
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      
      
      VEHICLE_SERVICE_NAME: ${VEHICLE_SERVICE_NAME}
      
    ports:
      - "8082:8080"
    depends_on:
      - vehicle-db
    networks:
      - vehicle-network
    restart: unless-stopped
    command: >
      sh -c "sleep 45 && dotnet VehicleService.API.dll"

networks:
  vehicle-network:
    driver: bridge

volumes:
  vehicle_db_data: